### ISSUE TITLE
explore if feasible to sync with FB Groups

### ISSUE THREAD

**Issue by amyxzhang** [haystack/murmur#63]
For people that want to access the mailing list via a FB group as opposed to email or web, is it feasible to create a FB group for the group and post all posts and replies to the group? The posts could come from the users if they've synced to FB - otherwise they would be posted by the "murmur" user/org account with the email/name of the author in the text. Posts made from FB should propagate to murmur also.

Questions:
- possible to create groups via API?
- does FB API allow you to subscribe to a group automatically?
- does FB API allow you to post on behalf of user in a group?
- can you get all discussions made in a FB group?

**Comment by kmahar** [comment]
Ok, I have been doing some research on this. 

So it seems like the way this works is that you have to make a Facebook application that users can authorize to post on their behalf. Most people use a lot of these apps already and sometimes let them post. (For example, I allow Spotify to post the songs I listen to.) 

It seems like the ["game groups"](https://developers.facebook.com/docs/games/services/game-groups) Facebook allows could actually be a really good fit. It's mainly intended for people who play video games together to have associated Facebook groups, but I think it has all the functionality we would need. You can make FB groups using the API and make users admins. (The downside of this is that the group admin would have to use FB.  It's not clear what happens if you post to the group creation API and don't specify an admin, or if the game/app itself can be the admin.) You can add users to the group via the API and then they will get a Facebook notification saying "Murmur has invited you to join x."The app can post in the group, both on behalf of users who authorize it and as its own entity. And the API can read posts and comments in the group's feed.

**Comment by kmahar** [comment]
There is a [third-party SDK for Django ](http://django-facebook.readthedocs.org/en/latest/index.html) we could potentially use

**Comment by kmahar** [comment]
I've been looking into IFTTT too - some notes:

- it probably won't be of any use for FB as none of the triggers involve actions in groups and none of the actions involve groups
-no discourse.org channel
-email channel allows you to send emails to take actions or get emailed about certain actions
-slack channel allows you to post to slack. no triggers on slack

**Comment by amyxzhang** [comment]
Closing this issue. Any further discussion of feasibility will move to #91
